# Author: Greedysky <greedysky@163.com>

name: CI-Build

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  ubuntu:
    uses: ./.github/workflows/ubuntu.yml
    secrets: inherit

  linux:
    uses: ./.github/workflows/linux.yml
    secrets: inherit

  winXP:
    uses: ./.github/workflows/winXP.yml
    secrets: inherit

  win:
    uses: ./.github/workflows/win.yml
    secrets: inherit

  doxygen:
    uses: ./.github/workflows/doxygen.yml
    secrets: inherit
