# Author: Greedysky <greedysky@163.com>

name: CI-Build-Library

on:
  workflow_dispatch:

jobs:
  linux:
    uses: ./.github/workflows/library_linux.yml
    secrets: inherit

  win:
    uses: ./.github/workflows/library_win.yml
    secrets: inherit
