# Author: Greedysky <greedysky@163.com>

name: library_linux

on: workflow_call

jobs:
  build:
    name: Build on gcc
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]

    env:
      INSTALL_PATH: /home/runner/work/TTKMusicPlayer/install/gcc

    runs-on: ${{matrix.os}}
    steps:
      - name: Install dependencies
        run: |
          sudo apt install libfuse2 p7zip-full
          sudo apt install texinfo rename
          sudo apt install libgl1-mesa-dev

      - name: Install thirdParty dependencies
        run: |
          wget https://github.com/Greedysky/TTKMusicPlayer/releases/download/continuous-build/qmmp-extra-pkg.7z
          7z x qmmp-extra-pkg.7z
        working-directory: ${{runner.workspace}}

      - name: Build library for libadlmidi
        run: |
          7z x libADLMIDI-1.6.1.7z -olibadlmidi
          cd libadlmidi
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_PATH}}/libadlmidi -DCMAKE_C_FLAGS="-fPIC -O3" -DCMAKE_CXX_FLAGS="-fPIC -O3" -DUSE_NUKED_EMULATOR=OFF -DUSE_OPAL_EMULATOR=OFF -DUSE_JAVA_EMULATOR=OFF -DUSE_ESFMU_EMULATOR=OFF -DUSE_MAME_EMULATOR=OFF -DUSE_YMFM_EMULATOR=OFF
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libbinio
        run: |
          7z x libbinio-1.5.7z -olibbinio
          cd libbinio
          autoreconf --install
          ./configure --prefix=${{env.INSTALL_PATH}}/libadplug CFLAGS="-fPIC -O3" CXXFLAGS="-fPIC -O3" --enable-static --enable-maintainer-mode
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libadplug
        run: |
          7z x adplug-2.4.7z -olibadplug
          cd libadplug
          export PKG_CONFIG_PATH=${{env.INSTALL_PATH}}/libadplug/lib/pkgconfig:$PKG_CONFIG_PATH
          ./configure --prefix=${{env.INSTALL_PATH}}/libadplug CFLAGS="-fPIC -O3" CXXFLAGS="-fPIC -O3" --enable-static --disable-shared
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libsndfile
        run: |
          7z x libsndfile-1.2.2.7z -olibsndfile
          cd libsndfile
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_PATH}}/libsndfile -DCMAKE_C_FLAGS="-fPIC -O3" -DCMAKE_CXX_FLAGS="-fPIC -O3"
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libbs2b
        run: |
          7z x libbs2b-3.1.0.7z -olibbs2b
          cd libbs2b
          export PKG_CONFIG_PATH=${{env.INSTALL_PATH}}/libsndfile/lib/pkgconfig:$PKG_CONFIG_PATH
          ./configure --prefix=${{env.INSTALL_PATH}}/libbs2b CFLAGS="-fPIC -O3" CXXFLAGS="-fPIC -O3" --enable-static CPPFLAGS="-I${{env.INSTALL_PATH}}/libsndfile/include" LDFLAGS="-L${{env.INSTALL_PATH}}/libsndfile/lib -lm"
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libcddb
        run: |
          7z x libcddb-1.3.2.7z -olibcddb
          cd libcddb
          ./configure --prefix=${{env.INSTALL_PATH}}/libcddb CFLAGS="-fPIC -O3" CXXFLAGS="-fPIC -O3" --enable-static --disable-shared --without-cdio
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libcdio
        run: |
          7z x libcdio-2.1.0.7z -olibcdio
          cd libcdio
          ./autogen.sh
          ./configure --prefix=${{env.INSTALL_PATH}}/libcdio CFLAGS="-fPIC -O3" CXXFLAGS="-fPIC -O3" --enable-static --disable-shared --disable-cxx --disable-example-progs --disable-cddb --without-cd-drive --without-cd-info --without-cdda-player --without-iso-info --without-iso-read --without-cd-read
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libcdio-paranoia
        run: |
          7z x libcdio-paranoia-10.2+2.0.1.7z -olibcdio-paranoia
          cd libcdio-paranoia
          export PKG_CONFIG_PATH=${{env.INSTALL_PATH}}/libcdio/lib/pkgconfig:$PKG_CONFIG_PATH
          ./configure --prefix=${{env.INSTALL_PATH}}/libcdio CFLAGS="-fPIC -O3" CXXFLAGS="-fPIC -O3" --enable-static --disable-shared --disable-cxx --disable-example-progs
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libenca
        run: |
          7z x enca-1.21.7z -olibenca
          cd libenca
          ./configure --prefix=${{env.INSTALL_PATH}}/libenca CFLAGS="-fPIC -O3" CXXFLAGS="-fPIC -O3" --enable-static --disable-shared
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libfaad2
        run: |
          7z x faad2-2.11.2.7z -olibfaad2
          cd libfaad2
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_PATH}}/libfaad2 -DCMAKE_C_FLAGS="-fPIC -O3" -DCMAKE_CXX_FLAGS="-fPIC -O3"
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libspeex
        run: |
          7z x speex-1.2.1.7z -olibspeex
          cd libspeex
          ./autogen.sh
          ./configure --prefix=${{env.INSTALL_PATH}}/libspeex CFLAGS="-fPIC -O3" CXXFLAGS="-fPIC -O3" --enable-static --disable-shared
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libffmpeg
        run: |
          7z x ffmpeg-3.4.14.7z -olibffmpeg
          cd libffmpeg
          # fix operand type mismatch for `shr'
          wget https://raw.githubusercontent.com/FFmpeg/FFmpeg/refs/heads/master/libavcodec/x86/mathops.h -O libavcodec/x86/mathops.h
          export PKG_CONFIG_PATH=${{env.INSTALL_PATH}}/libspeex/lib/pkgconfig:$PKG_CONFIG_PATH
          ./configure --prefix=${{env.INSTALL_PATH}}/libffmpeg --enable-shared --disable-static --disable-debug --disable-doc --disable-avdevice --disable-x86asm --disable-network --disable-encoders --disable-indevs --disable-outdevs --disable-iconv --disable-bsfs --disable-programs --disable-d3d11va --disable-dxva2 --disable-muxers --disable-parsers --disable-filters --disable-decoders --enable-decoder=wmav1 --enable-decoder=wmav2 --enable-decoder=ape --enable-decoder=tta --enable-decoder=aac --enable-decoder=alac --enable-decoder=ra_144 --enable-decoder=ra_288 --enable-decoder=shorten --enable-decoder=eac3 --enable-decoder=dca --enable-decoder=truehd --enable-decoder=twinvq --enable-decoder=tak --enable-decoder=adpcm_adx --enable-decoder=pcm_alaw --enable-decoder=pcm_s16be --enable-decoder=pcm_s16le --enable-decoder=gsm --enable-decoder=amrnb --enable-decoder=amrwb --enable-decoder=opus --enable-decoder=ac3 --enable-decoder=mp2 --enable-decoder=mp3 --enable-decoder=dsd_lsbf --enable-decoder=dsd_msbf --enable-decoder=vorbis --enable-decoder=flac --enable-decoder=libspeex --enable-libspeex --extra-cflags="-fPIC -O3" --extra-cxxflags="-fPIC -O3"
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libogg
        run: |
          7z x libogg-1.3.6.7z -olibogg
          cd libogg
          ./configure --prefix=${{env.INSTALL_PATH}}/libogg CFLAGS="-fPIC -O3" CXXFLAGS="-fPIC -O3" --enable-static --disable-shared
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libflac
        run: |
          7z x flac-1.5.0.7z -olibflac
          cd libflac
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_PATH}}/libflac -DCMAKE_PREFIX_PATH=${{env.INSTALL_PATH}}/libogg -DCMAKE_C_FLAGS="-fPIC -O3" -DCMAKE_CXX_FLAGS="-fPIC -O3" -DENABLE_64_BIT_WORDS=OFF -DENABLE_MULTITHREADING=OFF -DWITH_FORTIFY_SOURCE=OFF -DWITH_STACK_PROTECTOR=OFF
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libgme
        run: |
          7z x libgme-0.6.4.7z -olibgme
          cd libgme
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_PATH}}/libgme -DCMAKE_C_FLAGS="-fPIC -O3" -DCMAKE_CXX_FLAGS="-fPIC -O3" -DBUILD_SHARED_LIBS=OFF
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libmpcdec
        run: |
          7z x libmpcdec_r475.7z -olibmpcdec
          cd libmpcdec
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_PATH}}/libmpcdec -DCMAKE_C_FLAGS="-fPIC -O3" -DSHARED=OFF
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libmpg123
        run: |
          7z x mpg123-1.33.4.7z -olibmpg123
          cd libmpg123
          ./configure --prefix=${{env.INSTALL_PATH}}/libmpg123 CFLAGS="-fPIC -O3" CXXFLAGS="-fPIC -O3" --enable-static --disable-shared
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libopenmpt
        run: |
          7z x libopenmpt-0.4.52.7z -olibopenmpt
          cd libopenmpt
          ./configure --prefix=${{env.INSTALL_PATH}}/libopenmpt CFLAGS="-fPIC -O3" CXXFLAGS="-fPIC -O3" --enable-static --disable-shared --without-zlib --without-mpg123 --without-ogg --without-vorbis --without-vorbisfile --without-pulseaudio --without-portaudio --without-portaudiocpp --without-sndfile --without-flac
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for liboptimfrog
        run: |
          7z x OptimFROG_5100.7z -oliboptimfrog
          cd liboptimfrog/linux64
          sh install.sh ${{env.INSTALL_PATH}}/liboptimfrog
        working-directory: ${{runner.workspace}}

      - name: Build library for libopus
        run: |
          7z x opus-1.6.1.7z -olibopus
          cd libopus
          ./configure --prefix=${{env.INSTALL_PATH}}/libopusfile CFLAGS="-fPIC -O3" CXXFLAGS="-fPIC -O3" --enable-static --disable-shared --disable-extra-programs
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libopusfile
        run: |
          7z x opusfile-0.12.7z -olibopusfile
          cd libopusfile
          export PKG_CONFIG_PATH=${{env.INSTALL_PATH}}/libogg/lib/pkgconfig:${{env.INSTALL_PATH}}/libopusfile/lib/pkgconfig:$PKG_CONFIG_PATH
          ./configure --prefix=${{env.INSTALL_PATH}}/libopusfile CFLAGS="-fPIC -O3" CXXFLAGS="-fPIC -O3" --enable-static --disable-shared --disable-http --disable-doc
          make -j2 && make install
          # add opus header patch
          sed -i "s/<opus_/<opus\/opus_/g" ${{env.INSTALL_PATH}}/libopusfile/include/opus/opusfile.h
        working-directory: ${{runner.workspace}}

      - name: Build library for libprojectm
        run: |
          if [ ${{matrix.os}} == "ubuntu-22.04" ]; then
            echo "projectm build for ubuntu 22.04"
            7z x libprojectm-2.2.1.7z -olibprojectm
          else
            echo "projectm build for ubuntu 24.04"
            7z x -snld libprojectm-2.2.1.7z -olibprojectm
          fi
          cd libprojectm
          ./autogen.sh
          ./configure --prefix=${{env.INSTALL_PATH}}/libprojectm CFLAGS="-fPIC -O3 -DDISABLE_NATIVE_PRESETS" CXXFLAGS="-fPIC -O3 -DDISABLE_NATIVE_PRESETS" --enable-static --disable-shared
          make -j2 && make install
          # fix install headers
          mkdir ${{env.INSTALL_PATH}}/libprojectm/include/libprojectM
          mv ${{env.INSTALL_PATH}}/libprojectm/include/*.h* ${{env.INSTALL_PATH}}/libprojectm/include/libprojectM
        working-directory: ${{runner.workspace}}

      - name: Build library for libsamplerate
        run: |
          7z x libsamplerate-0.2.2.7z -olibsamplerate
          cd libsamplerate
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_PATH}}/libsamplerate -DCMAKE_C_FLAGS="-fPIC -O3"
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libsidplayfp
        run: |
          7z x libsidplayfp-2.3.1.patch.7z -olibsidplayfp
          cd libsidplayfp
          ./configure --prefix=${{env.INSTALL_PATH}}/libsidplayfp CFLAGS="-fPIC -O3" CXXFLAGS="-fPIC -O3" --enable-static --disable-shared
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libsoxr
        run: |
          7z x soxr-0.1.3.7z -olibsoxr
          cd libsoxr
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_PATH}}/libsoxr -DCMAKE_C_FLAGS="-fPIC -O3" -DCMAKE_CXX_FLAGS="-fPIC -O3" -DBUILD_SHARED_LIBS=OFF
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libtaglib
        run: |
          7z x taglib-1.13.1.7z -olibtaglib
          cd libtaglib
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_PATH}}/libtaglib -DCMAKE_C_FLAGS="-fPIC -O3" -DCMAKE_CXX_FLAGS="-fPIC -O3" -DWITH_ZLIB=OFF
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libvorbis
        run: |
          7z x libvorbis-1.3.7.7z -olibvorbis
          cd libvorbis
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_PATH}}/libvorbis -DCMAKE_PREFIX_PATH=${{env.INSTALL_PATH}}/libogg -DCMAKE_C_FLAGS="-fPIC -O3" -DCMAKE_CXX_FLAGS="-fPIC -O3"
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libwavpack
        run: |
          7z x wavpack-5.9.0.7z -olibwavpack
          cd libwavpack
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_PATH}}/libwavpack -DCMAKE_C_FLAGS="-fPIC -O3" -DCMAKE_CXX_FLAGS="-fPIC -O3"
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libxmp
        run: |
          7z x libxmp-4.6.3-patch.7z -olibxmp
          cd libxmp
          ./configure --prefix=${{env.INSTALL_PATH}}/libxmp CFLAGS="-fPIC -O3" CXXFLAGS="-fPIC -O3" --enable-static --disable-shared --disable-depackers --disable-prowizard
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build library for libsunvox
        run: |
          7z x sunvox-2.1.4.7z -olibsunvox
          cd libsunvox
          mkdir ${{env.INSTALL_PATH}}/libsunvox
          mv linux/x64/sunvox.so ${{env.INSTALL_PATH}}/libsunvox
        working-directory: ${{runner.workspace}}

      - name: Build library for libttk
        run: |
          7z x ttk-1.2.12.7z -olibttk
          cd libttk
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{env.INSTALL_PATH}}/libttk -DCMAKE_C_FLAGS="-fPIC -O3" -DCMAKE_CXX_FLAGS="-fPIC -O3"
          make -j2 && make install
        working-directory: ${{runner.workspace}}

      - name: Build thirdParty libraries package
        run: |
          # rename all libraries name to static
          find . -type f -name "*.a" -exec rename 's/\.a$/_static.a/' {} +
          # add portable binary package
          7z a thirdParty-libraries-${{matrix.os}}-x64.7z
        working-directory: ${{runner.workspace}}/install

      - name: Archive artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: continuous-build
          token: ${{secrets.GITHUB_TOKEN}}
          generate_release_notes: false
          files: ${{runner.workspace}}/install/thirdParty-libraries-${{matrix.os}}-x64.7z
